export const landingPages = {
  sell: {
    eyebrow: 'Sell',
    title: 'Sell with better visibility',
    subtitle: 'List your property through Arch9 and connect the journey from first enquiry to registration.',
    cta: 'Start selling',
    href: '/contact',
    metaTitle: 'Sell Property | Arch9',
  },
  agents: {
    eyebrow: 'Agents',
    title: 'One workspace for modern estate agents',
    subtitle: 'Manage leads, listings, offers, documents, buyers, sellers, and transactions in one connected platform.',
    cta: 'Book a demo',
    href: '/contact',
    metaTitle: 'Estate Agent Software | Arch9',
  },
  attorneys: {
    eyebrow: 'Attorneys',
    title: 'Transfer matters, connected to the full transaction',
    subtitle: 'Keep agents, buyers, sellers, and finance partners aligned from instruction to registration.',
    cta: 'Book a demo',
    href: '/contact',
    metaTitle: 'Conveyancing Transaction Software | Arch9',
  },
  'bond-originators': {
    eyebrow: 'Bond Originators',
    title: 'Bond applications, connected from day one',
    subtitle: 'Receive cleaner applications, track bank submissions, and keep every stakeholder updated.',
    cta: 'Book a demo',
    href: '/contact',
    metaTitle: 'Bond Originator Software | Arch9',
  },
  developers: {
    eyebrow: 'Developers',
    title: 'Launch and manage developments with Arch9',
    subtitle: 'Connect stock, buyers, agents, finance, documents, and sales progress in one place.',
    cta: 'Book a demo',
    href: '/contact',
    metaTitle: 'Property Developer Software | Arch9',
  },
  platform: {
    eyebrow: 'Platform Overview',
    title: 'One property journey. One shared workspace.',
    subtitle: 'Arch9 connects buyers, sellers, agents, attorneys, bond originators, and developers around a single transaction spine.',
    cta: 'Explore the platform',
    href: '/platform/overview',
    metaTitle: 'Platform Overview | Arch9',
  },
  commercial: {
    eyebrow: 'Commercial Property',
    title: 'Commercial property, connected to the full journey',
    subtitle: 'Bring commercial listings, enquiries, documents, stakeholders, and transaction progress into one shared Arch9 workspace.',
    cta: 'Book a demo',
    href: '/contact',
    metaTitle: 'Commercial Property | Arch9',
  },
  'why-arch9': {
    eyebrow: 'Why Arch9',
    title: 'Property transactions need shared infrastructure',
    subtitle: 'Arch9 connects the people, documents, updates, and decisions that move a property journey from first enquiry to registration.',
    cta: 'Explore the platform',
    href: '/platform',
    metaTitle: 'Why Arch9 | Arch9',
  },
  help: {
    eyebrow: 'Help Centre',
    title: 'Help for every step of the property journey',
    subtitle: 'Find guidance for listings, enquiries, documents, transaction progress, and stakeholder collaboration on Arch9.',
    cta: 'Contact support',
    href: 'mailto:hello@arch9.co.za',
    secondaryLabel: 'View platform',
    secondaryHref: '/platform',
    metaTitle: 'Help Centre | Arch9',
  },
  docs: {
    eyebrow: 'Documentation',
    title: 'Arch9 documentation for connected property teams',
    subtitle: 'Explore setup guidance, workflows, and platform documentation for teams building their transaction process around Arch9.',
    cta: 'Book a demo',
    href: '/contact',
    secondaryLabel: 'View platform',
    secondaryHref: '/platform',
    metaTitle: 'Documentation | Arch9',
  },
  privacy: {
    eyebrow: 'Privacy Policy',
    title: 'Privacy built for a connected property journey',
    subtitle: 'Learn how Arch9 approaches personal information, transaction context, and responsible data handling across the platform.',
    cta: 'Contact us',
    href: '/contact',
    secondaryLabel: 'View platform',
    secondaryHref: '/platform',
    metaTitle: 'Privacy Policy | Arch9',
  },
  terms: {
    eyebrow: 'Terms of Service',
    title: 'Terms for using Arch9',
    subtitle: 'Review the terms that apply when teams, clients, and partners use Arch9 to coordinate property transactions.',
    cta: 'Contact us',
    href: '/contact',
    secondaryLabel: 'View platform',
    secondaryHref: '/platform',
    metaTitle: 'Terms of Service | Arch9',
  },
  security: {
    eyebrow: 'Security',
    title: 'Security for shared transaction workspaces',
    subtitle: 'Arch9 is designed around clear access, role-aware collaboration, and responsible handling of property transaction information.',
    cta: 'Discuss security',
    href: '/contact',
    secondaryLabel: 'View platform',
    secondaryHref: '/platform',
    metaTitle: 'Security | Arch9',
  },
  cookies: {
    eyebrow: 'Cookies',
    title: 'Cookie preferences and website data',
    subtitle: 'Learn how Arch9 may use cookies and similar technologies to improve website performance, analytics, and visitor experience.',
    cta: 'Contact us',
    href: '/contact',
    secondaryLabel: 'View platform',
    secondaryHref: '/platform',
    metaTitle: 'Cookies | Arch9',
  },
  finance: {
    eyebrow: 'Finance Hub',
    title: 'Finance tools for the full buying journey',
    subtitle: 'Use Arch9 to estimate repayments, check affordability, prepare documents, request cost breakdowns, and start a finance application.',
    cta: 'Apply For Finance',
    href: '/contact',
    secondaryLabel: 'Browse properties',
    secondaryHref: '/',
    metaTitle: 'Finance Hub | Arch9',
  },
  'buyer-dashboard': {
    eyebrow: 'Buyer Dashboard',
    title: 'Your property journey in one account',
    subtitle: 'Saved properties, viewing requests, offer status, finance applications, document requests, and notifications will live in one Arch9 dashboard.',
    cta: 'Book a demo',
    href: '/contact',
    secondaryLabel: 'Browse properties',
    secondaryHref: '/',
    metaTitle: 'Buyer Dashboard | Arch9',
  },
  'registration-tracking': {
    eyebrow: 'Registration Tracking',
    title: 'Track every milestone after the offer is accepted',
    subtitle: 'Arch9 gives buyers a live view of bond approval, transfer attorney assignment, documents, guarantees, lodgement, and registration.',
    cta: 'Explore the platform',
    href: '/platform',
    secondaryLabel: 'Browse properties',
    secondaryHref: '/',
    metaTitle: 'Registration Tracking | Arch9',
  },
  alerts: {
    eyebrow: 'Property Alerts',
    title: 'Never miss the right property',
    subtitle: 'Create alerts for price bands, bedroom counts, locations, developments, saved areas, and status changes across the Arch9 network.',
    cta: 'Start browsing',
    href: '/',
    secondaryLabel: 'View platform',
    secondaryHref: '/platform',
    metaTitle: 'Property Alerts | Arch9',
  },
}
