export const solutionPages = {
  agents: {
    eyebrow: 'For agents',
    title: 'Turn listings into registrations.',
    subtitle: 'Generate enquiries, qualify buyers and manage every transaction from listing to registration - all in one place.',
    primaryCta: 'List A Property',
    secondaryCta: 'Book A Demo',
    sectionHeading: 'Everything an agent needs to close more deals.',
    workflowTitle: 'Listing to commission, connected.',
    workflow: ['Listing live', 'Buyer enquiry', 'Offer accepted', 'Bond approved', 'Transfer', 'Registration', 'Commission paid'],
    visualLabel: 'Agent workspace',
    metrics: [
      { value: '14', label: 'Active buyers' },
      { value: '3', label: 'Offers received' },
      { value: '1', label: 'Transfer in progress' },
    ],
    features: [
      'More qualified buyer enquiries',
      'Buyer matching',
      'Offer tracking',
      'Transaction visibility',
      'Client updates',
      'Document management',
      'Faster commission progress',
    ],
    metaTitle: 'Estate Agent Software | Arch9',
    metaDescription: 'Generate enquiries, qualify buyers and manage every property transaction from listing to registration with Arch9.',
  },
  attorneys: {
    eyebrow: 'For attorneys',
    title: 'Cleaner instructions. Fewer follow-ups. Better matters.',
    subtitle: 'Receive structured transfer, bond and cancellation instructions with documents, roleplayers and transaction context already connected.',
    primaryCta: 'Book A Demo',
    sectionHeading: 'Built for transfer, bond and cancellation teams.',
    workflowTitle: 'Matter intake with the context already attached.',
    workflow: ['Instruction received', 'Roleplayers linked', 'Documents requested', 'Bond status aligned', 'Transfer milestones', 'Registration update'],
    visualLabel: 'Matter workspace',
    metrics: [
      { value: '42%', label: 'Less chasing' },
      { value: '1', label: 'Shared matter view' },
      { value: '24/7', label: 'Status visibility' },
    ],
    features: [
      'Cleaner matter instructions',
      'Buyer and seller documents upfront',
      'Linked transfer, bond and cancellation matters',
      'Roleplayer visibility',
      'Milestone updates',
      'Reduced chasing',
      'Better client communication',
    ],
    metaTitle: 'Conveyancing Transaction Software | Arch9',
    metaDescription: 'Receive cleaner transfer, bond and cancellation instructions with documents, roleplayers and transaction context connected.',
  },
  'bond-originators': {
    eyebrow: 'For bond originators',
    title: 'Cleaner bond applications from day one.',
    subtitle: 'Receive better buyer information, manage bank submissions and keep agents updated throughout the finance journey.',
    primaryCta: 'Book A Demo',
    sectionHeading: 'From application to approval, fully connected.',
    workflowTitle: 'Finance progress every stakeholder can follow.',
    workflow: ['Buyer captured', 'Documents collected', 'Consultant assigned', 'Submitted to banks', 'Approval tracked', 'Agent updated'],
    visualLabel: 'Bond workspace',
    metrics: [
      { value: '5', label: 'Bank submissions' },
      { value: '86%', label: 'Complete applications' },
      { value: 'Live', label: 'Agent updates' },
    ],
    features: [
      'Structured buyer applications',
      'Document collection',
      'Bank submission tracking',
      'Consultant assignment',
      'Agent updates',
      'Application progress visibility',
      'Partner routing',
    ],
    metaTitle: 'Bond Originator Software | Arch9',
    metaDescription: 'Manage structured buyer applications, document collection, bank submissions and agent updates with Arch9.',
  },
  developers: {
    eyebrow: 'For developers',
    title: 'Sell development stock with more visibility and control.',
    subtitle: 'Showcase developments, capture buyer interest, support agents and track sales progress from enquiry to registration.',
    primaryCta: 'List A Development',
    secondaryCta: 'Book A Demo',
    sectionHeading: 'A better way to launch and manage developments.',
    workflowTitle: 'From launch campaign to registered sale.',
    workflow: ['Development published', 'Units available', 'Buyer enquiry', 'Agent assigned', 'Offer accepted', 'Sale progressing', 'Registration'],
    visualLabel: 'Development workspace',
    metrics: [
      { value: '79', label: 'Units visible' },
      { value: '18', label: 'Buyer enquiries' },
      { value: '6', label: 'Agents active' },
    ],
    features: [
      'Development showcase pages',
      'Unit availability',
      'Buyer enquiries',
      'Agent distribution',
      'Sales progress tracking',
      'Lead management',
      'Project-level reporting',
    ],
    metaTitle: 'Property Developer Software | Arch9',
    metaDescription: 'Showcase developments, capture buyer interest, support agents and track development sales progress with Arch9.',
  },
  platform: {
    eyebrow: 'Platform overview',
    title: 'One shared transaction spine for property.',
    subtitle: 'Arch9 connects buyers, sellers, agents, attorneys, bond originators and developers around one shared property transaction.',
    primaryCta: 'See How It Works',
    secondaryCta: 'Book A Demo',
    sectionHeading: 'Every role connected around one transaction.',
    workflowTitle: 'One transaction spine from search to registration.',
    workflow: ['Property search', 'Buyer and seller portals', 'Agent CRM', 'Bond applications', 'Attorney matters', 'Documents', 'Milestones'],
    visualLabel: 'Shared transaction spine',
    metrics: [
      { value: '6', label: 'Roles connected' },
      { value: '1', label: 'Shared timeline' },
      { value: 'Live', label: 'Milestone updates' },
    ],
    features: [
      'Property search',
      'Buyer and seller portals',
      'Agent CRM',
      'Bond applications',
      'Attorney matters',
      'Document management',
      'Transaction milestones',
      'Roleplayer collaboration',
    ],
    metaTitle: 'Platform Overview | Arch9',
    metaDescription: 'Arch9 connects every property role around one shared transaction spine from search to registration.',
  },
}
